### ISSUE TITLE
new application not showing up in the dashbaord

### ISSUE THREAD

**Issue by WelltokCaleb** [yvasiyarov/gorelic#31]
I've added gorelic as middleware, and can see that it is sending data to NewRelic, and that NR is returning a 200....but when I check my NR page, the app is not listed. I've been told NR should automatically create the new app when it receives the data. Just curious if you know if I need to do something on the NR side to start receiving and showing this data?

**Comment by sethhochberg** [comment]
We're seeing the same thing on our end. Interestingly, I do see our app reporting under the "Plugins" section of NewRelic, in the GoRelic category, so I'm not sure I've just misunderstood the way gorelic is expected to update or if there is actually an issue to be resolved.

**Comment by WelltokCaleb** [comment]
I'm not seeing it under Plugins, either. As far as I can tell, these messages just get dropped.

**Comment by seenickcode** [comment]
Seeing this too.  Any new findings yet, @WelltokCaleb ?

**Comment by WelltokCaleb** [comment]
@seenickcode: Sadly, no...haven't made any progress.

**Comment by jordanshoebox** [comment]
@sethhochberg If you see your app under Plugins, are you seeing the headings in the left panel (Memory In Use, GC, SysMemUsage, ...)? If you do see those, are you just not seeing data in the graphs?

@WelltokCaleb If you don't see your app under plugins, are you sure you've got it configured correctly? Set up with the correct licence key, started the agent, etc?

**Comment by WelltokCaleb** [comment]
@jordanshoebox - yep. We're using NewRelic for a bunch of existing apps (nodeJS and Ruby, primarily) without issue, and I'm using the same key, etc.

**Comment by sethhochberg** [comment]
@jordanshoebox Yes, we do see the correct headings and also the graphs displaying under the Plugin menu. What is specifically missing in our case is the APM reporting.

**Comment by WelltokCaleb** [comment]
@jordanshoebox - might have been a timing issue. Several days after last checking, the GoRelic app is listed in the Plugins, so we're at the same place as @sethhochberg.

**Comment by paritosh90** [comment]
@sethhochberg @WelltokCaleb  Was there any progress on this. We are facing the same issue. I can see Gorelic app in the Plugins, but not in APM.

**Comment by mikegleasonjr** [comment]
I am now using the official go APM plugin (which is in beta) and quite loving it. It appears in the APM and not in the plugins section.
