### ISSUE TITLE
HTTP status stats are not collected

### ISSUE THREAD

**Issue by ezbercih** [yvasiyarov/gorelic#39]
I turned it on by setting CollectHTTPStatuses to true for my agent instance but I do not see this data being collected. Looking at how you are wrapping HTTP handlers, I am not sure if you can ever collect it. You are handing over the ResponseWriter instance to the next handler in line and lose handle on it, unless I am reading this wrong. Is there a working example of this anywhere?

**Comment by yvasiyarov** [comment]
@ezbercih please, have a look at http_metrics.go:35.
```defer handler.timer.UpdateSince(startTime)```
will be executed after any handlers, and we dont need ResponseWriter instance to update metrics

**Comment by ezbercih** [comment]
This still doesn't answer my question or actually solves my problem. I am not getting any stats on HTTP statuses. Do you have a working example where metrics on HTTP statuses are collected successfully?

**Comment by jaihind213** [comment]
hi i have submitted a PR to resolve this:
https://github.com/yvasiyarov/gorelic/pull/56

**Comment by yvasiyarov** [comment]
@jaihind213 thanks a lot! PR merged!
