### ISSUE TITLE
This metrica was not implemented yet for darwin

### ISSUE THREAD

**Issue by shalakhin** [yvasiyarov/gorelic#4]
Hi!

First of all thank you a lot for the package gorelic! :+1: 

I am programming my project on Mac and running it with gorelic package I am getting error: "This metrica was not implemented yet for darwin".

Logs with errors below:

```
2013/12/21 01:36:31 Can not get metrica: Runtime/System/Threads, got error:&errors.errorString{s:"This metrica was not implemented yet for darwin"}
2013/12/21 01:36:31 Can not get metrica: Runtime/System/FDSize, got error:&errors.errorString{s:"This metrica was not implemented yet for darwin"}
2013/12/21 01:36:31 Can not get metrica: Runtime/System/Memory/VmPeakSize, got error:&errors.errorString{s:"This metrica was not implemented yet for darwin"}
2013/12/21 01:36:31 Can not get metrica: Runtime/System/Memory/VmCurrent, got error:&errors.errorString{s:"This metrica was not implemented yet for darwin"}
2013/12/21 01:36:31 Can not get metrica: Runtime/System/Memory/RssPeak, got error:&errors.errorString{s:"This metrica was not implemented yet for darwin"}
2013/12/21 01:36:31 Can not get metrica: Runtime/System/Memory/RssCurrent, got error:&errors.errorString{s:"This metrica was not implemented yet for darwin"}
```

**Comment by sammy007** [comment]
Please make it silent, just write this log once at first attempt to get metrics, not all the time while running app.

**Comment by nazwa** [comment]
Those errors are really annoying actually. How about simply adding (the already existing in agent) verbose parameter to the component as well?

https://github.com/nazwa/newrelic_platform_go/commit/b6835a5b64eded8c0bcff2e55de7570421c2687e#diff-bfadacbd0b869750828e287887f1e85f

This worked quite well so far for me, but I'd prefer to come back onto your module instead of my fork :smile:

**Comment by yvasiyarov** [comment]
@nazwa can you, please, send me the pull request ?

**Comment by rtyer** [comment]
This was bugging me, so I went ahead and tossed @nazwa's solution to that in a PR.

**Comment by nazwa** [comment]
Sorry guys, was away yesterday and couldn't PR this. The only drawback of this solution is that if there is an "actual" error, it will also be silenced. 

Don;t forget that https://github.com/yvasiyarov/gorelic/blob/master/agent.go#L133 needs to be updated as well to include the verbose parameter when creating a component.

**Comment by rtyer** [comment]
+1 @nazwa 

Sorry, should have submitted the PR for this change, too.

**Comment by nazwa** [comment]
@rtyer you seem to have started a chain of uncontrollable events by trying to recreate my 'fix' haha

**Comment by rtyer** [comment]
:-(

**Comment by thellimist** [comment]
this is still active

**Comment by Hokutosei** [comment]
@yvasiyarov I am developing on mac, but deploying on a linux env. how do I disable this log? `verbose == false` already, but this error is still displaying. can you please take a look?

**Comment by morenoh149** [comment]
bump not sure if this has been solved or I'm just a couple of versions behind
