### ISSUE TITLE
Per-host metrics?

### ISSUE THREAD

**Issue by dcelasun** [yvasiyarov/gorelic#40]
Is it possible to see metrics on a per-host basis while using the same application name in multiple servers? This is possible with New Relic's own agents, I was wondering if gorelic could do the same.

**Comment by yvasiyarov** [comment]
@dcelasun unfortunately NewRelic's own agent use totally different API, which is much more reach than NewRelic Plugin API.
NewRelic Plugin API does not provide per host monitoring possibility. Or I'm not aware about it.
