### ISSUE TITLE
Difficulty setting up

### ISSUE THREAD

**Issue by calebthompson** [yvasiyarov/gorelic#47]
I've followed the directions to set up GoRelic, but I'm not seeing the analytics in NewRelic.

Here's the code, called from the `main` func, that I'm using to initialize:

``` go
func configureNewrelic() {
       agent := gorelic.NewAgent()
       agent.Verbose = true
       agent.NewrelicLicense = os.Getenv("NEW_RELIC_LICENSE_KEY")
       agent.Run()
}
```

The license key variable is present on Heroku (I'm using the addon).

In the app's logs, I see data being generated: https://gist.github.com/calebthompson/9fdf1cceda41264fc93c

However, the NewRelic dashboard is empty for this app (I get the setup screen) and NewRelic's support seems to feel that they're not getting any data.

I realize issues are an awful way of asking for help, but help?

**Comment by tylerb** [comment]
I am having the same problem. Did you find a solution?

**Comment by tylerb** [comment]
I found the data - it's under the "Plugins" section of New Relic. Perhaps this is your problem also, @calebthompson?

**Comment by calebthompson** [comment]
I'll check thanks!

**Comment by vsouza** [comment]
I have the same problem.

**Comment by calebthompson** [comment]
I found the plugin under Plugins, but there's no data.

@yvasiyarov any thoughts?

**Comment by thellimist** [comment]
@calebthompson I found the data under plugins too. Maybe your license is wrong?

**Comment by ssymbol** [comment]
Mine shows up under Plugins, thanks @tylerb 
@calebthompson Firewall or outbound tcp contraints?

**Comment by mrichman** [comment]
Navigate to Plugins -> GoRelic

![2016-07-20_16-26-04](https://cloud.githubusercontent.com/assets/11228/17001867/cb844534-4e96-11e6-97ba-13e840bd75aa.png)
